### ISSUE TITLE
Failed to install adventr

### ISSUE THREAD

**Issue by FedeFontana** [profandyfield/adventr#10]
Hi Andy, 

I'm trying to practice R using your package but when I try to install it I got an error:
 
_"Installing 49 packages: tidyverse, learnr, car, effects, lm.beta, robust, sjstats, WRS2, ellipsis, vctrs, lifecycle, isoband, farver, askpass, sys, httpuv, xtable, sourcetools, later, promises, fastmap, openxlsx, zip, minqa, nloptr, numDeriv, mitools, DEoptimR, robustbase, pcaPP, insight, bayestestR, parameters, estimability, sjlabelled, rappdirs, shiny, renv, carData, rio, lme4, survey, fit.models, rrcov, effectsize, emmeans, performance, sjmisc, mc2d
Error: Failed to install 'adventr' from GitHub:
  (converted from warning) dependency ‘pbkrtest’ is not available"_

In addition, when I try to install the "discovr" ones I got another error: 
_"> install_github("profandyfield/discovr")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found
  Did you spell the repo owner (`profandyfield`) and repo name (`discovr`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
>"_

**Comment by profandyfield** [comment]
pbkrtest is a dependency of one of the packages used inadventr. Not sure why it's saying it isn't available - it looks like it is up to date and so on ([https://cran.r-project.org/web/packages/pbkrtest/index.html](https://cran.r-project.org/web/packages/pbkrtest/index.html)). You could try doing a manual install of that package and then try adventr again. Also would be useful to know your `sessionInfo()`

discovr is in development - it's not ready to install yet. The repo is private until it is, that's why it won't install. It'll be released with the new edition of the R book (I'm working on both simultaneously).

a.

**Comment by FedeFontana** [comment]
Thanks for your support. 
It worked.

Is there a way to access the data you mentioned in your youtube video "practical class workflow" even though I'm not registered as a student within Sussex university?

**Comment by profandyfield** [comment]
I would ignore that video and work through this newer intro to R/RStudio: [http://milton-the-cat.rocks/learnr/r/r_getting_started/#section-working-in-rstudio](http://milton-the-cat.rocks/learnr/r/r_getting_started/#section-working-in-rstudio)

It's more of a general intro and less-specific to my classes. Good luck!
